// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/validate"
)

func decodeTestResponse(resp *http.Response) (res *TestOK, err error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &TestOK{}, nil
	}
	return res, validate.UnexpectedStatusCode(resp.StatusCode)
}
