// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Test implements test operation.
//
// Test.
//
// POST /test
func (UnimplementedHandler) Test(ctx context.Context, req *User) error {
	return ht.ErrNotImplemented
}
